"""Add userId to searches

Revision ID: ca81d3604249
Revises: 287a5173df08
Create Date: 2024-07-31 14:57:34.541365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca81d3604249'
down_revision = '287a5173df08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_searches_userId_users'), 'users', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_searches_userId_users'), type_='foreignkey')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
